name: Hello World

on:
  push:
    branches:
      - master 

jobs:
  run-hello-world:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

          
